controller_manager:
  ros:
    parameters:
      update_rate: 100  # Hz

      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster

      diff_drive_controller:
        type: diff_drive_controller/DiffDriveController

diff_drive_controller:
  ros__parameters:
    left_wheel_names: [ "left_wheel_joint" ]
    right_wheel_names: [ "right_wheel_joint" ]

    wheel_separation: 0.20  # Distance between wheels (0.1m + 0.1m from center)
    wheel_radius: 0.05      # Radius of the wheels

    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0

    publish_rate: 50.0
    odom_frame_id: odom
    base_frame_id: base_link

    # Enable cmd_vel input
    use_stamped_vel: false
    # Enable publishing of odometry
    publish_odom: true
    publish_odom_tf: true
